### PR TITLE
drawio link addition under diagram

### PR DESCRIPTION
**Pull request by ddooley**

### CODE REVIEW

**Comment by jamesaoverton** [comment]
The ontodev site is only for testing, I don't want permanent links to it. Can this link

https://www.draw.io/#Uhttps%3A%2F%2Fobi-ontology.ontodev.com%2Fassets%2Fimages%2Fdocs%2Fcore-classes%2Fcore-classes.drawio

point to GitHub or raw.githubusercontent.com instead?

**Comment by ddooley** [comment]
Done!

**Comment by ddooley** [comment]
I tweaked it to point to where file will be in obi-ontology.org site, ok?

**Comment by jamesaoverton** [comment]
Let's find out!

**Comment by jamesaoverton** [comment]
Unfortunately I got "Error loading file: File not found" on draw.io. Ah, it has to be `http` not `https` for the embedded link, then it works. Fixed in f659ae855166fdfe57a04a84a279126645201343

**Pull request merged**
