### PR TITLE
Incremental docs

### PR DESCRIPTION
**Pull request by jamesaoverton**
I'm turning this branch into a PR so I can add comments and get notifications. As usual, I'm in a rush, so I apologize if this is too curt.

## General comments:

- As long as the PR's title contains "WIP" for "work in progress", it's not yet ready to merge. So don't merge it. I'll do that.
- Smaller changes are much easier to review than large changes. I often have a 15-minute block free to look at a page and hit "merge", but I rarely have a 1-hour block free to read several pages and puzzle about their interactions.
- Every moving piece is something that can break. Let's have as few as possible.

## Developer Instructions

This repo has a `README.md`. Developer-facing instructions for testing this site locally should go there, not public-facing `index.md`.

## Ruby

For all the other GitHub Pages sites I use, just locally running `jekyll serve` with a `_config.yml` gives you everything locally that's available in GitHub Pages. I don't think we need `Gemfile` or `Gemfile.lock` or Bundler.

## History

Git contains the full history of all files. If we don't need `obi-old.css` any more, then please delete it.

## Markdown

I don't want `{:target="_blank"}` on every link. In a few weeks it will be 2020, so we should assume that people know how to use a web browser.

## File Names

A few years from now, life will be much easier if we can easily find the source `drawio` file for given `png`. Can you please make the file naming and locations more consistent?

### CODE REVIEW

**Comment by ddooley** [comment]
Ok, good to know about "jeckyll serve"; gem stuff dropped. obi-old.css gone; markdown adjusted. About drawio file - I propose each be named then by the name of the page its graphics appear on. I'll do that this weekend.

**Comment by jamesaoverton** [comment]
I updated this preview site: https://obi-ontology.ontodev.com/

**Comment by jamesaoverton** [comment]
I reviewed all the pages, simplified some of the text, and adjusted some of the style. In particular, I only want to use backticks for code and file names, not for term labels. The OBO convention is to use single-quotes around term labels.

**Comment by jamesaoverton** [comment]
Thanks @ddooley !

**Comment by ddooley** [comment]
Sweet.  Now should every new pull request for a doc page be prefixed with WIP ?

**Comment by jamesaoverton** [comment]
My preference is to use the "[WIP]" prefix until the PR is ready to be reviewed and merged. In other words, if you're still making changes, mark it as work in progress.

**Pull request merged**
